[tool.poetry]
name = "cryptowallet"
version = "0.1.0"
description = ""
authors = ["spogins <spogins@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.100.1"
uvicorn = "^0.23.2"
dependency-injector = "^4.41.0"
sqlalchemy = "^2.0.19"
psycopg2 = "^2.9.6"
passlib = "^1.7.4"
email-validator = "^2.0.0.post2"
pyjwt = {extras = ["crypto"], version = "^2.8.0"}
pydantic = "^2.1.1"
responses = "^0.23.3"
fastapi-mail = "^1.4.1"
celery = {extras = ["redis"], version = "^5.3.1"}
redis = "^4.6.0"
aioredis = "2.0.0"
propan = {extras = ["async-rabbit"], version = "^0.1.5.17"}
broker = "^0.3.3"
rabbitmq = "^0.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
