"""migration

Revision ID: 23a43d08cdbe
Revises: ec0ea6531138
Create Date: 2023-09-23 19:03:47.504869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23a43d08cdbe'
down_revision: Union[str, None] = 'ec0ea6531138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('is_object', sa.Boolean(), nullable=True))
    op.add_column('block', sa.Column('is_object', sa.Boolean(), nullable=True))
    op.add_column('blockchain', sa.Column('is_object', sa.Boolean(), nullable=True))
    op.add_column('chat_message', sa.Column('is_object', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('is_object', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('is_object', sa.Boolean(), nullable=True))
    op.add_column('transaction', sa.Column('is_object', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_object', sa.Boolean(), nullable=True))
    op.add_column('wallet', sa.Column('is_object', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'is_object')
    op.drop_column('user', 'is_object')
    op.drop_column('transaction', 'is_object')
    op.drop_column('product', 'is_object')
    op.drop_column('order', 'is_object')
    op.drop_column('chat_message', 'is_object')
    op.drop_column('blockchain', 'is_object')
    op.drop_column('block', 'is_object')
    op.drop_column('asset', 'is_object')
    # ### end Alembic commands ###
