"""migration

Revision ID: 7f437c661ec1
Revises: 0ee821785517
Create Date: 2023-09-18 13:55:00.755838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f437c661ec1'
down_revision: Union[str, None] = '0ee821785517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'PENDING', 'FAILED', name='transactionstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_id'), 'status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_id'), table_name='status')
    op.drop_table('status')
    # ### end Alembic commands ###
